version: "3"
services:
  app:
    build: go
    env_file: ".env"
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    build: postgres
    env_file: ".env"
    restart: always
    ports:
      - "5432:5432"
