version: "3"
services:
  app:
    build: go
    env_file: ".env"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app-network
  postgres:
    build: postgres
    env_file: ".env"
    restart: always
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
networks:
  app-network:
volumes:
  postgres-data:
