version: "3"
services:
  app:
    build: go
    env_file: ".env"
    ports:
      - "1111:3000"
    depends_on:
      - postgres
  postgres:
    build: postgres
    env_file: ".env"
    restart: always
    ports:
      - "2222:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "3333:6379"
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "4444:8080"
    volumes:
      - ./swagger.yaml:/usr/share/nginx/html/swagger.yaml
    environment:
      URL: swagger.yaml
  swagger-editor:
    image: swaggerapi/swagger-editor
    volumes:
      - ./swagger.yaml:/tmp/swagger.yaml
    environment:
      SWAGGER_FILE: /tmp/swagger.yaml
    ports:
      - "5555:8080"
  node:
    build: node
    ports:
      - "7777:7777"
volumes:
  postgres-data:
